#可以使用这个文件配置,每一项用空格隔开，不能用tab
#如果存在application.properties文件，则用application.properties，否则会使用application.yml
#yml文件也可以用yaml做后缀名
server:
    port: 8083
    #Property 'server.context-path' is Deprecated: Use 'server.servlet.context-path' instead.
    #context-path: /webdemo1
    servlet.context-path: /bootweb
    
